services:
  iptv-au:
    container_name: iptv-au
    build:
      context: .
      dockerfile: Dockerfile
    pull_policy: build
    environment:
      - REGION=all
    ports:
      - 8183:80
    restart: unless-stopped
